# Docker compose to start up required services for local development

name: transitdata-partial-apc-pipeline
services:
  apache-pulsar:
    image: apachepulsar/pulsar:3.0.0
    platform: linux/arm64
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - pulsarconf:/pulsar/conf
      - pulsardata:/pulsar/data
    command: bin/pulsar standalone

  mqtt-pulsar-gateway:
    image: hsldevcom/mqtt-pulsar-gateway:develop
    network_mode: "host"
    depends_on:
      - apache-pulsar
    restart: unless-stopped
    environment:
      PULSAR_HOST: host.docker.internal
      MQTT_BROKER_HOST: tcp://mqtt.hsl.fi:1883
      MQTT_TOPIC: /hfp/v2/journey/ongoing/partial-apc/#

  transitdata-hfp-parser:
    image: hsldevcom/transitdata-hfp-parser:develop
    network_mode: "host"
    depends_on:
      - mqtt-pulsar-gateway
    restart: unless-stopped
    environment:
      PULSAR_HOST: host.docker.internal
      PULSAR_CONSUMER_TOPIC: mqtt-raw
      PULSAR_PRODUCER_TOPIC: hfp-topic

volumes:
  pulsarconf:
  pulsardata:
