---
services:
  pulsar:
    image: "apachepulsar/pulsar:latest"
    restart: "unless-stopped"
    command: "bin/pulsar standalone"
    ports:
      - "127.0.0.1:6650:6650"
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "bin/pulsar-admin brokers healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10

  pulsar-manager:
    image: "apachepulsar/pulsar-manager:latest"
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
    ports:
      - "127.0.0.1:7750:7750"
      - "127.0.0.1:9527:9527"
    environment:
      - "SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties"
      - "PULSAR_PEEK_MESSAGE=true"

  set-pulsar-manager-user:
    image: "apachepulsar/pulsar-manager:latest"
    restart: "on-failure"
    depends_on:
      pulsar-manager:
        condition: service_started
    entrypoint: /set-pulsar-manager-user.sh
    environment:
      # As pulsar-manager is only available from localhost, we can use silly
      # credentials.
      - "USERNAME=admin"
      - "PASSWORD=apachepulsar"
    volumes:
      - ./config/set-pulsar-manager-user/set-pulsar-manager-user.sh:/set-pulsar-manager-user.sh:ro
    network_mode: "host"

  mosquitto-apc:
    image: eclipse-mosquitto:latest
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:1883:1883"
    healthcheck:
      test:
        [
          "CMD",
          "mosquitto_sub",
          "-p",
          "1883",
          "-t",
          "$$SYS/#",
          "-C",
          "1",
          "-i",
          "healthcheck",
          "-W",
          "3",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/mosquitto-apc/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  vehicle-db:
    image: "postgres:latest"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    volumes:
      - ./config/vehicle-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./config/vehicle-db/transitlogDbEquipment.csv:/transitlogDbEquipment.csv:ro

  # Use docker-compose logs collect-apc-results to read the messages.
  collect-apc-results:
    image: eclipse-mosquitto:latest
    restart: "unless-stopped"
    depends_on:
      mosquitto-apc:
        condition: service_healthy
    command: "mosquitto_sub --host mosquitto-apc --port 1883 --qos 2 --topic '/hfp/v2/journey/ongoing/apc/#' -I collect-apc --verbose"

  transitdata_partial_apc_mqtt_pulsar_gateway_1:
    image: hsldevcom/mqtt-pulsar-gateway:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      transitdata_partial_apc_mqtt_deduplicator:
        condition: service_started
    environment:
      - MQTT_MAX_INFLIGHT=300000
      - PULSAR_CONSUMER_SUBSCRIPTION_TYPE=Exclusive
      - PULSAR_HOST=127.0.0.1
      - PULSAR_PORT=6650
      - MQTT_BROKER_HOST=tcp://localhost:61883
      - "MQTT_TOPIC=/hfp/v2/journey/ongoing/apc-partial/#"
      - "MQTT_CLIENT_ID=transitdata_partial_apc_mqtt_pulsar_gateway_test_1"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-mqtt-raw-partial-apc"
      - "HEALTH_ENABLED=false"
      - UNHEALTHY_MSG_SEND_INTERVAL_SECS=3
      - MQTT_ADD_RANDOM_TO_CLIENT_ID=true
    healthcheck:
      disable: true # remove/comment test if using disable
      #test: curl -f http://localhost:8090/health || exit 1
      interval: 60s
      timeout: 3s
      retries: 2
    network_mode: "host"

  transitdata_partial_apc_mqtt_pulsar_gateway_2:
    image: hsldevcom/mqtt-pulsar-gateway:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      transitdata_partial_apc_mqtt_deduplicator:
        condition: service_started
    environment:
      - MQTT_MAX_INFLIGHT=300000
      - PULSAR_CONSUMER_SUBSCRIPTION_TYPE=Exclusive
      - PULSAR_HOST=127.0.0.1
      - PULSAR_PORT=6650
      - MQTT_BROKER_HOST=tcp://localhost:61883
      - "MQTT_TOPIC=/hfp/v2/journey/ongoing/apc-partial/#"
      - "MQTT_CLIENT_ID=transitdata_partial_apc_mqtt_pulsar_gateway_test_2"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-mqtt-raw-partial-apc"
      - "HEALTH_ENABLED=false"
      - UNHEALTHY_MSG_SEND_INTERVAL_SECS=3
      - MQTT_ADD_RANDOM_TO_CLIENT_ID=true
    healthcheck:
      disable: true # remove/comment test if using disable
      #test: curl -f http://localhost:8090/health || exit 1
      interval: 60s
      timeout: 3s
      retries: 2
    network_mode: "host"

  transitdata_partial_apc_mqtt_deduplicator:
    image: hsldevcom/transitdata-hfp-deduplicator:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
    environment:
      - PULSAR_HOST=pulsar
      - PULSAR_PORT=6650
      - "PULSAR_CONSUMER_TOPIC=persistent://public/default/hfp-mqtt-raw-partial-apc"
      - "PULSAR_CONSUMER_SUBSCRIPTION=transitdata_partial_apc_mqtt_deduplicator"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-mqtt-raw-deduplicated-partial-apc"
      - "HEALTH_ENABLED=true"
    healthcheck:
      #disable: true # remove/comment test if using disable
      test: curl -f http://localhost:8090/health || exit 1
      interval: 15s
      timeout: 10s
      retries: 3

  transitdata_partial_apc_pbf_json_transformer:
    image: hsldevcom/transitdata-apc-protobuf-json-transformer:edge
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      transitdata_partial_apc_pulsar_mqtt_gateway:
        condition: service_started
    environment:
      - "HEALTH_CHECK_PORT=8080"
      - "PULSAR_BLOCK_IF_QUEUE_FULL=true"
      - "PULSAR_COMPRESSION_TYPE=LZ4"
      - "PULSAR_CONSUMER_TOPIC=persistent://public/default/hfp-expanded-apc"
      - "PULSAR_SUBSCRIPTION=transitdata_partial_apc_protobuf_json_transformer"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-expanded-apc-mqtt-backfeed"
      - "PULSAR_SERVICE_URL=pulsar://pulsar:6650"
    healthcheck:
      #disable: true # remove/comment test if using disable
      test: curl -f http://localhost:8080/healthz || exit 1
      interval: 10s
      timeout: 5s
      retries: 2

  transitdata_partial_apc_pulsar_mqtt_gateway:
    image: hsldevcom/pulsar-mqtt-gateway:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      mosquitto-apc:
        condition: service_healthy
    environment:
      - PULSAR_CONSUMER_SUBSCRIPTION_TYPE=Exclusive
      - MQTT_MAX_INFLIGHT=10000
      - PULSAR_HOST=pulsar
      - PULSAR_PORT=6650
      - MQTT_BROKER_HOST=tcp://mosquitto-apc:1883
      - "MQTT_TOPIC=/hfp/v2/journey/ongoing/apc/bus" # use topicSuffix, e.g. "0123/12345"
      - "PULSAR_CONSUMER_TOPIC=persistent://public/default/hfp-expanded-apc-mqtt-backfeed"
      - "MQTT_RETAIN_MESSAGE=false"
      - "PULSAR_CONSUMER_SUBSCRIPTION=transitdata_partial_apc_pulsar_mqtt_gateway"
      - "MQTT_CLIENT_ID=transitdata_partial_apc_pulsar_mqtt_gateway"
      - "MQTT_HAS_AUTHENTICATION=false"
      - "HEALTH_ENABLED=true"
    healthcheck:
      #disable: true # remove/comment test if using disable
      test: curl -f http://localhost:8090/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 2

  transitdata_hfp_mqtt_pulsar_gateway_1:
    image: hsldevcom/mqtt-pulsar-gateway:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      transitdata_hfp_mqtt_deduplicator:
        condition: service_started
    environment:
      - PULSAR_CONSUMER_SUBSCRIPTION_TYPE=Exclusive
      - MQTT_MAX_INFLIGHT=300000
      - PULSAR_HOST=127.0.0.1
      - PULSAR_PORT=6650
      - MQTT_BROKER_HOST=tcp://localhost:49876
      - "MQTT_TOPIC=/hfp/v2/#"
      - "MQTT_CLIENT_ID=transitdata_hfp_mqtt_pulsar_gateway_test_1"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-mqtt-raw-v2"
      - "MAX_MESSAGES_PER_SECOND=1800"
      - "HEALTH_ENABLED=false"
      - UNHEALTHY_MSG_SEND_INTERVAL_SECS=3
      - MQTT_ADD_RANDOM_TO_CLIENT_ID=true
    healthcheck:
      disable: true # remove/comment test if using disable
      #test: curl -f http://localhost:8090/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 2
    network_mode: "host"

  transitdata_hfp_mqtt_pulsar_gateway_2:
    image: hsldevcom/mqtt-pulsar-gateway:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      transitdata_hfp_mqtt_deduplicator:
        condition: service_started
    environment:
      - PULSAR_CONSUMER_SUBSCRIPTION_TYPE=Exclusive
      - MQTT_MAX_INFLIGHT=300000
      - PULSAR_HOST=127.0.0.1
      - PULSAR_PORT=6650
      - MQTT_BROKER_HOST=tcp://localhost:49876
      - "MQTT_TOPIC=/hfp/v2/#"
      - "MQTT_CLIENT_ID=transitdata_hfp_mqtt_pulsar_gateway_test_2"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-mqtt-raw-v2"
      - "MAX_MESSAGES_PER_SECOND=1800"
      - "HEALTH_ENABLED=false"
      - UNHEALTHY_MSG_SEND_INTERVAL_SECS=5
      - MQTT_ADD_RANDOM_TO_CLIENT_ID=true
    healthcheck:
      disable: true # remove/comment test if using disable
      #test: curl -f http://localhost:8090/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 2
    network_mode: "host"

  transitdata_hfp_mqtt_deduplicator:
    image: hsldevcom/transitdata-hfp-deduplicator:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
      transitdata_hfp_parser:
        condition: service_started
    environment:
      - PULSAR_HOST=pulsar
      - PULSAR_PORT=6650
      - "PULSAR_CONSUMER_TOPIC=persistent://public/default/hfp-mqtt-raw-v2"
      - "PULSAR_CONSUMER_SUBSCRIPTION=transitdata_hfp_mqtt_deduplicator"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-mqtt-raw-deduplicated-v2"
      - "HEALTH_ENABLED=true"
    healthcheck:
      disable: true # remove/comment test if using disable
      # test: curl -f http://localhost:8090/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 2

  transitdata_hfp_parser:
    image: hsldevcom/transitdata-hfp-parser:develop
    restart: "unless-stopped"
    depends_on:
      pulsar:
        condition: service_healthy
    environment:
      - PULSAR_HOST=pulsar
      - PULSAR_PORT=6650
      - "PULSAR_CONSUMER_TOPIC=persistent://public/default/hfp-mqtt-raw-deduplicated-v2"
      - "PULSAR_CONSUMER_SUBSCRIPTION=transitdata_hfp_parser"
      - "PULSAR_PRODUCER_TOPIC=persistent://public/default/hfp-v2"
      - "HEALTH_ENABLED=false"
      - "DEBUG_ENABLED=true"
    healthcheck:
      disable: true # remove/comment test if using disable
      #test: curl -f http://localhost:8090/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 2
