---
name: "CI/CD: Continuous integration and continuous deployment"

"on":
  push:
    branches:
      - main
      - hotfix/**
    tags:
      - "v*"
  pull_request:

env:
  IMAGE_NAME_MIXEDCASE: "${{ github.repository }}"
  TEST_STAGE: tester
  PRODUCTION_STAGE: production

jobs:
  build-check-test-push:
    name: Build, check, test, push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract Pulsar version from package.json
        run: |
          echo "PULSAR_VERSION=$(jq -r '.config.pulsarVersion' < ./package.json)" >> "${GITHUB_ENV}"
      - name: Lowercase Docker image name
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME_MIXEDCASE,,}" >> "${GITHUB_ENV}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha,format=long
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.TRANSITDATA_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITDATA_DOCKERHUB_TOKEN }}
      - name: Build and push
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || contains(github.ref, 'refs/tags/'))
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: "${{ env.PRODUCTION_STAGE }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
